### PR TITLE
Support Angular 15

### LINKED ISSUE #86: Angular 15 Support
dependency support for @angular/common@"^15.0.2"

### PR DESCRIPTION
**Pull request by SarcevicAntonio**
# this is closed, because I'm no longer interested in this getting merged 

Closes #86 

* Upgrades library and playground to Angular 15 via `ng update`
  * Includes the removal of `.browserlistrc`, as it macthes the Angular CLI default configuration
  * Includes removal of `defaultProject` option from playground workspace configuration
* Added generated temporary files from playground folder to `.gitignore`
* Bump library version via `npm version patch`
* Confirmed that playground still works

### CODE REVIEW

**Review by aldrashan — APPROVED** [review]

**Comment by aldrashan** [comment]
Could we get this merged and published?
Want to update our code to Angular 15 so we can start testing but this dependency is preventing us from doing so.

**Comment by SarcevicAntonio** [comment]
> Could we get this merged and published? Want to update our code to Angular 15 so we can start testing but this dependency is preventing us from doing so.

I ended up just coping the library code to our codebase, since it's not that much and maintainer seems to be absent ATM

**Review by StuderAaron — APPROVED** [review]

**Review by StuderAaron — APPROVED** [review]

**Comment by hakimio** [comment]
@SarcevicAntonio you have to update peer dependencies as well:
https://github.com/vdolek/angular-resize-event/blob/d577ba9f01ba675e5e149971e0016ea7b2010fb7/projects/angular-resize-event/package.json#L20

**Comment by 10Bude10** [comment]
When will it be merged?

**Comment by thatcort** [comment]
@SarcevicAntonio Hi, noticed this PR was closed without being merged. Is there a plan for Angular 15 support?

**Comment by SarcevicAntonio** [comment]
> @SarcevicAntonio Hi, noticed this PR was closed without being merged. Is there a plan for Angular 15 support?

Hello. I'm not a maintainer for this project therefore I can't speak about what the plans going forward are. As I said [above](https://github.com/vdolek/angular-resize-event/pull/89#issuecomment-1352780741) we removed the dependency via copy paste, because this project seems to be not maintained and it blocked upgrading angular.

**Pull request closed without merging**
