### PR TITLE
Updated peer dependencies

### PR DESCRIPTION
**Pull request by tdhulster**
Updated peer dependencies so there's a little more flexibility in the usage of this package and get rid of some build warnings 💪 
Currently using in an application that runs on :
- Angular 9
- RxJS 6.5.x
- Core-js 2.6.x

Hope you're ok with this!

### CODE REVIEW

**Comment by tdhulster** [comment]
You can tryout the ranges I've used here : https://semver.npmjs.com/

**Comment by richard-ob** [comment]
@vdolek Would you be able to review this and approve? As per my testing, it seems correct.

**Comment by richard-ob** [comment]
Thanks @vdolek! Much appreciated. Does this require a manual npm publish from you, or will this happen automatically?

**Comment by vdolek** [comment]
Sorry for the delay. Published.

**Pull request merged**
